### ISSUE TITLE
Problems with ESP32-S2

### ISSUE THREAD

**Issue by berodimas** [sparkfun/SparkFun_MLX90640_Arduino_Example#24]
Hello everyone,

Is there any possible way to use this sensor with ESP32-S2? I've trying any kind of configuration but still got this output:

`MLX90640 IR Array Example
MLX90640 online!
Parameter extraction failed
Pixel 0: nanC
Pixel 1: nanC
Pixel 2: nanC
Pixel 3: nanC
Pixel 4: nanC
Pixel 5: nanC
Pixel 6: nanC
Pixel 7: nanC
Pixel 8: nanC
Pixel 9: nanC
Pixel 0: nanC
Pixel 1: nanC`

also if I change the wire clock to 100khz, I got the GetFrame Error: -8 on serial monitor.

**Comment by nseidle** [comment]
ESP32 S2 core is not yet respecting repeated start.

Below is good transaction with ESP32:
![image](https://user-images.githubusercontent.com/117102/136858744-b309be1d-c82f-4635-b20d-644fdc29c9ce.png)

Below is bad trasnaction with ESP32-S2:

![image](https://user-images.githubusercontent.com/117102/136858781-a0500ee4-38d9-4251-a4f0-2c0b249b1fef.png)

The sensor is reporting an extra 0x0009 at the beginning of the read most likely because the S2 is releasing the bus (with a stop command) right before it initiates a read (this is bad).

[Known issue](https://github.com/espressif/arduino-esp32/issues/4729#issuecomment-922737664) that is currently slated for v2.0.1 of ESP32 Arduino core. If you can't wait, pull the most recent ESP32 Arduino core. There are fixes in place that resolve the problem.
